### ISSUE TITLE
(u)pBibTeX j0.35 (TeX Live 2023/dev)拡張のマニュアル化

### ISSUE THREAD

**Issue by t-tk** [texjporg/pbibtex-manual#3]
bibtexuの日本語(CJK)対応 https://github.com/texjporg/tex-jp-build/issues/139 に関連して (u)pbibtex もいくつか拡張しました。
TeX Live 2023に入る予定でして、それに伴うマニュアルの更新です。
TeX Live 2023 のコードフリーズの頃にmasterにマージしてCTAN投稿しようと思います。
推敲などあれば何なりとどうぞ。

- `int.to.chr$`, `chr.to.int$` 関数の拡張
- `change.case$` 関数の拡張 (upbibtexのみ)
- `max_print_line` の kpathsearchライブラリ変数化 (bibtex, pbibtex, upbibtex共通)
- `add.period$` の対象の句読点対応扱い文字に U+203D (‽, Interrobang) を追加 (upbibtexのみ)

**Comment by t-tk** [comment]
tests/jxampl/* に入れたテストは bibtexu の結果を含んでいますが、
bibtexu の場合は jxampl.bib, jbtxdoc.bib, j*.bst などの文字コードを UTF-8 変換にしないと動きません。

Ref. 文字コードを JIS → UTF-8 に?
https://github.com/texjporg/pbibtex-base/issues/2

**Comment by t-tk** [comment]
TeX Live 2023 のコードフリーズが近づいてきているのでそろそろCTAN投稿しようと思います。
CTANのfinal updateまであと2週間ほどしか時間がありません。
@aminophen さんがすでにここのブランチpbib-upbib-tl2023を master にマージされたようですがどうしましょうか。
私がしましょうか?

```
Plan for TeX Live 2023:
10feb: candidate/final sources committed, test builds begin.
17feb: tlpretest starts, CTAN updates continue there and in tlnet.
3mar: code freeze for final build, major bug fixes only.
10mar: final updates from CTAN, final doc tweaks.
12mar: deliver TL image for TeX Collection packaging/testing.
19mar: public release (also of MacTeX).
May?: delivery of TeX Collection DVD to members.
```

**Comment by aminophen** [comment]
ptex-manual を近々出そうと思っているので，私の方でまとめて送ることもできます。どちらも Karl さんに頼んで tlnet には入れず tlpretest だけをお願いする必要がありますね。

**Comment by t-tk** [comment]
了解です。それではお願いします。

**Comment by aminophen** [comment]
CTAN に上げました。
